#!/bin/bash
# =========================================
# .FILE
#   download
#
# .SYNOPSIS
#   download apps larger than 100MB
#
# .DESCRIPTION
#   You can download:
#     - MPLABX-v6.20-linux-downloader.tar
#     - Proteus 8.13 SP0 Pro.zip
#     - PS2 Games (GTA, PES2014, ...)
#     - PCSX2 (ps2 emulator)
#
# .PARAMETER $app_name
#   The application name that you want to download
#
# .INPUTS
#   app_name
#
# .OUTPUTS
#   app package
#
# .NOTES
#   Version       : 1.0
#   Author        : @ZouariOmar <zouariomar20@gmail.com>
#   Created       : 07/17/2025
#   Change Log    : Initial version
#
# .EXAMPLE
#   ./download mplabx
# =========================================
app_name=$1
EXIT_SUCCES=0
EXIT_FAILED=1

help() {
  echo -e """
    [FILE]
      download - bash file
    [SYNOPSIS]
      download apps larger than 100MB
    [DESCRIPTION]
      You can download:
        - MPLABX-v6.20-linux-downloader.tar                 -- ./download mplabx
        - Proteus 8.13 SP0 Pro.zip                          -- ./download proteus
        - PS2 Games                                         -- ./download ps2
        - PCSX2-v2.4.0                                      -- ./download pcsx2
        - Netacad Resource Hub (e.g Cisco Packet Tracer..)  -- ./download netcad
        - Counter-Strike 1.6                                -- ./download cs1.6
    [AUTHOR]
      @ZouariOmar (zouariomar20@gmail.com)
    [CREATED]
      17/07/2025
    [USAGE]
      ./download <app_name>
    [EXAMPLE]
      ./download mplabx
  """
}

if [[ $# -ne 1 ]]; then
  help
  exit $EXIT_FAILED
fi

download_mplabx() {
  echo -e """
  [LINK00] https://www.microchip.com/en-us/tools-resources/develop/mplab-x-ide#tabs
  """
  exit $EXIT_SUCCES
}

download_proteus() {
  echo -e """
  [LINK00] https://pesktop.com/en/windows/proteus_professional
  [LINK01] https://drive.google.com/file/d/18dc8n0lpLu9QRzxbgZzciAwhg6NeqnPp/view
  """
  exit $EXIT_SUCCES
}

download_ps2_games() {
  echo -e """
  [LINK00] Grand Theft Auto: San Andreas  -- https://romsfun.com/download/grand-theft-auto-san-andreas-id-1-12950/4
  [LINK01] PES 2014: Pro Evolution Soccer -- https://romsfun.com/download/pes-2014-pro-evolution-soccer-88777
  """
  exit $EXIT_SUCCES
}

download_pcsx2() {
  wget https://github.com/PCSX2/pcsx2/releases/download/v2.4.0/pcsx2-v2.4.0-linux-appimage-x64-Qt.AppImage
}

download_netcad_resource_hub() {
  echo -e """
  [LINK00] Resource Hub -- https://www.netacad.com/resources/lab-downloads?courseLang=en-US
  """
  exit $EXIT_SUCCES
}

download_cs() {
  wget https://csdownload.net/?download_file=https://cstrike.csdownload.net/cstrike2025.exe || exit $EXIT_FAILED
  exit $EXIT_SUCCES
}

case $app_name in
"mplabx")
  download_mplabx
  ;;
"proteus")
  download_mplabx
  ;;
"ps2")
  download_ps2_games
  ;;
"pcsx2")
  download_pcsx2
  ;;
"netcad")
  download_netcad_resource_hub
  ;;
"cs1.6")
  download_cs
  ;;
*)
  help
  ;;
esac
